
USE cinemawebpage;
DROP TABLE IF EXISTS food_orders;
DROP TABLE IF EXISTS booking_details;
DROP TABLE IF EXISTS bookings;	
DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS showtimes;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS cinemas;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS foods;
